# Generated by Django 6.0.7 on 2026-07-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpamPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.TextField(verbose_name='Original Email Text')),
                ('cleaned_text', models.TextField(blank=True, null=True, verbose_name='Cleaned Preprocessed Text')),
                ('prediction_label', models.CharField(max_length=10, verbose_name='Prediction (Spam/Ham)')),
                ('confidence', models.FloatField(verbose_name='Confidence Score (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Prediction Date & Time')),
            ],
            options={
                'verbose_name': 'Spam Prediction',
                'verbose_name_plural': 'Spam Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
